/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Fax_incoming.java
 *
 * Created on Apr 8, 2010, 2:10:12 PM
 */

package cc_tunas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sun.database.JavaConnector;
import javax.swing.ImageIcon;
/**
 *
 * @author jsm
 */
public class Fax_incoming extends javax.swing.JFrame {
    public static int z;
    public static int zz;
    public static int fid=0;
    private String usrlvl;
    private String opdt;
    private String optm;
    public static int statuss;
    private String id;
    private String notic;

    /** Creates new form Fax_incoming */
    public Fax_incoming() {
        initComponents();
        showCust();
        setSize(1024,768);
    }

    public static ContactCenterTunas CCanj;
    public Fax_incoming(ContactCenterTunas ccanj){
        this();
        this.CCanj=ccanj;
    }
    public static Search_ticket Sct;
    public Fax_incoming(Search_ticket sct){
        this();
        this.Sct=sct;
    }
    private ticket Tic;
    public Fax_incoming(ticket tic){
        this();
        this.Tic=tic;
    }
    private FAX Fax;
    public Fax_incoming(FAX fax){
        this();
        this.Fax=fax;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblview = new javax.swing.JLabel();
        btnreply = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cbcust = new javax.swing.JComboBox();
        txtnotic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Incoming Fax viewer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        lblview.setBackground(new java.awt.Color(204, 204, 255));
        lblview.setOpaque(true);
        jScrollPane1.setViewportView(lblview);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(2, 2, 1020, 730);

        btnreply.setText("Reply");
        btnreply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreplyActionPerformed(evt);
            }
        });
        jPanel1.add(btnreply);
        btnreply.setBounds(939, 740, 70, 20);

        jButton2.setFont(new java.awt.Font("Calibri", 0, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tic.jpg"))); // NOI18N
        jButton2.setText("Open Ticket");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(160, 740, 133, 20);

        jButton1.setFont(new java.awt.Font("Calibri", 0, 12));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1245117595_001_37.png"))); // NOI18N
        jButton1.setText("Search Ticket");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 740, 131, 20);

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel16.setText("Cust. Company");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, 740, 100, 20);

        cbcust.setFont(new java.awt.Font("Calibri", 0, 12));
        cbcust.setMaximumRowCount(9);
        cbcust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        cbcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcustActionPerformed(evt);
            }
        });
        jPanel1.add(cbcust);
        cbcust.setBounds(410, 740, 200, 24);

        txtnotic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(txtnotic);
        txtnotic.setBounds(730, 740, 140, 24);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ticket No");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(630, 740, 100, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //zz=(Tic.id);
            if(fid!=0){
//                System.out.print(zz);
                if(zz==-1){
                sql = "update log_fax set"
                        + " _status=2, cust_name='"+cbcust.getSelectedItem()+"'"
                        + " ticket_no='"+txtnotic.getText()+"'"
                        + " where fax_id='"+fid+"'";
                CCanj.jconn.SQLExecute(sql, CCanj.conn);
                }else{
                    sql = "update log_fax set " +
                        "_status=2, cust_name='"+cbcust.getSelectedItem()+"' " +
                        ", ticket_id='"+zz+"'" +
                        "where fax_id='"+fid+"'";
                    CCanj.jconn.SQLExecute(sql, CCanj.conn);
//                    System.out.print(sql);
                }
            }
        CCanj.fax();
//        try {
//            conn.close();
//        } catch (SQLException ex) {
//            System.err.println(ex.getMessage());
//        }
    }//GEN-LAST:event_formWindowClosed

    private void btnreplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreplyActionPerformed
        // TODO add your handling code here:
        FAX1 com=new FAX1();
        com.setVisible(true);
//        Fax.txtcto.setText(txtto.getText());
}//GEN-LAST:event_btnreplyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ticket tic=new ticket();
        tic.setVisible(true);

        Tic.newtic=true;
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Search_ticket st=new Search_ticket();
        st.setVisible(true);
        Sct.mail=true;
}//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcustActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fax_incoming().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreply;
    public static javax.swing.JComboBox cbcust;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblview;
    public static javax.swing.JTextField txtnotic;
    // End of variables declaration//GEN-END:variables

    public static String sql;
    public static String sql1;
    public static ResultSet rs;
//    public static JavaConnector jconn=new JavaConnector();
//    public static Connection conn;

    public static void open(){
        sql = "select * from log_fax " +
                    "where _status=1 and _direction=0 " +
                    "and username='"+ CCanj.lbluser.getText()+"'";
            rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
            System.out.print("\n isi fax "+sql);
        try {
            while (rs.next()) {
                z++;
                fid=Integer.parseInt(rs.getString(1));
                lblview.setIcon(new ImageIcon("Z:/localhost/inbox/"+rs.getString(5).toString()+""));
                System.out.print("\n isi file "+rs.getString(5));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Fax_incoming.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void opdt(){
          try{
              sql="select CURRENT_DATE";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  opdt=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
    }
        private void optm(){
            try{
              sql="select CURRENT_TIME";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  optm=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
        }
        private void stt(){
                try{
                    sql="select _status from tickets where ticket_id='"+id+"' and ticket_no='"+notic+"'";
                    rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
                    while(rs.next()){
                        statuss=Integer.parseInt(rs.getString(1));
                    }
                }catch(Exception e){
                    System.out.print(e);
                }
            }
        private void showCust(){
        try{
            cbcust.removeAllItems();
            cbcust.addItem("Others");

            sql="select distinct(cust_name) from customer_order order by cust_name";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcust.addItem(rs.getString(1));
            }
        }catch(Exception e){
            System.out.println(e);

        }
    }
}
