/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OutBound.java
 *
 * Created on Feb 23, 2010, 11:03:52 PM
 */

package cc_tunas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.Timer;
import java.awt.*;
import java.awt.Event.*;
import java.awt.event.ActionEvent;
import java.sql.*;
import javax.sun.database.JavaConnector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.io.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import java.util.ArrayList;
import java.net.*;
/**
 *
 * @author jsm
 */
public class OutBound extends javax.swing.JFrame {

    public static int z;
    public static String zz;
    public static int oid=0;
    public static Timer ti;

    public static String loid;
    public static int conf;
    private static boolean running=false;
    private static boolean call=false;
    public static boolean obtic=false;
    private static long elapsed;
    private static long startTime=0;
    private static long stopTime=0;
    private static int submit;
    String optm;
    String opdt;

    private String pabx;
    private String in_ext;
    private String out_ext;
    public static int xxx=0;
    private String usrlvl;
     public static int status;
    public static int asdep;
    private String solution;
    /** Creates new form OutBound */
    public OutBound() {
        initComponents();
        usrlvl();
        showCaltype(); showCust();
    }

    private login Log;
    public OutBound(login log){
        this();
        this.Log=log;
    }
    public static ContactCenterTunas CCanj;
    public OutBound(ContactCenterTunas ccanj){
        this();
        this.CCanj=ccanj;
    }
    private ticket Tic;
    public OutBound(ticket tic){
        this();
        this.Tic=tic;
    }
    public Search_ticket Sct;
    public OutBound(Search_ticket sct){
        this();
        this.Sct=sct;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdialnm = new javax.swing.JTextField();
        txtdial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnhangup = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcomment = new javax.swing.JTextArea();
        btncall = new javax.swing.JButton();
        txtnotic1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        btnsrchcus = new javax.swing.JButton();
        cbcaltype = new javax.swing.JComboBox();
        ckconf = new javax.swing.JCheckBox();
        btnsave = new javax.swing.JButton();
        lbldurasi = new javax.swing.JLabel();
        btnopentic = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txtdial2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        cbcust = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtnotic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbcategory = new javax.swing.JComboBox();
        cbprior = new javax.swing.JComboBox();
        cbdept = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtcontract = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtcuscod = new javax.swing.JTextField();
        txtcusnam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcusfax = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcuspho = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtcustadd = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txtcuspic = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtcusconst = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtcusconend = new javax.swing.JTextField();
        btnsrchcus1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        txtcusconst1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtcsomail = new javax.swing.JTextField();
        txtcsopho = new javax.swing.JTextField();
        txtcso = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtcsocode = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtusr = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtusrpho = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtusraddr = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cbnoplat = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        txtjenis = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtwarna = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txttype = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtthn = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtdrinm = new javax.swing.JTextField();
        cbdriver = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        txtdripho1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdetails = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtsolution = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OUTBOUND CALL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OutBound Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel1.setText("Call Number");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 30, 100, 20);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 70, 100, 20);

        txtdialnm.setFont(new java.awt.Font("Calibri", 0, 12));
        txtdialnm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdialnmFocusLost(evt);
            }
        });
        jPanel1.add(txtdialnm);
        txtdialnm.setBounds(110, 70, 200, 24);

        txtdial.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel1.add(txtdial);
        txtdial.setBounds(110, 30, 150, 24);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel3.setText("Caller Type");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 100, 20);

        btnhangup.setFont(new java.awt.Font("Calibri", 0, 12));
        btnhangup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/4.jpg"))); // NOI18N
        btnhangup.setText("Hang UP");
        btnhangup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhangupMouseClicked(evt);
            }
        });
        btnhangup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangupActionPerformed(evt);
            }
        });
        jPanel1.add(btnhangup);
        btnhangup.setBounds(171, 460, 140, 24);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "comment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N

        txtcomment.setColumns(20);
        txtcomment.setFont(new java.awt.Font("Calibri", 0, 12));
        txtcomment.setLineWrap(true);
        txtcomment.setRows(5);
        jScrollPane2.setViewportView(txtcomment);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(9, 190, 300, 260);

        btncall.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btncall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3.jpg"))); // NOI18N
        btncall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncallActionPerformed(evt);
            }
        });
        jPanel1.add(btncall);
        btncall.setBounds(260, 30, 50, 39);

        txtnotic1.setFont(new java.awt.Font("Calibri", 0, 12));
        txtnotic1.setAutoscrolls(false);
        txtnotic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnotic1MouseClicked(evt);
            }
        });
        txtnotic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotic1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtnotic1);
        txtnotic1.setBounds(110, 130, 100, 24);

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel20.setText("Ticket Id.");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 130, 100, 20);

        btnclose.setFont(new java.awt.Font("Calibri", 0, 12));
        btnclose.setText("Close");
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
        });
        jPanel1.add(btnclose);
        btnclose.setBounds(10, 460, 80, 24);

        btnsrchcus.setFont(new java.awt.Font("Calibri", 0, 11));
        btnsrchcus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1245117595_001_37.png"))); // NOI18N
        btnsrchcus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsrchcusMouseClicked(evt);
            }
        });
        jPanel1.add(btnsrchcus);
        btnsrchcus.setBounds(210, 130, 20, 20);

        cbcaltype.setFont(new java.awt.Font("Calibri", 0, 12));
        cbcaltype.setMaximumRowCount(9);
        cbcaltype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        cbcaltype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcaltypeActionPerformed(evt);
            }
        });
        jPanel1.add(cbcaltype);
        cbcaltype.setBounds(110, 90, 200, 24);

        ckconf.setBackground(new java.awt.Color(204, 204, 255));
        ckconf.setFont(new java.awt.Font("Calibri", 0, 12));
        ckconf.setText("Confirmed");
        ckconf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckconfMouseClicked(evt);
            }
        });
        jPanel1.add(ckconf);
        ckconf.setBounds(110, 150, 100, 20);

        btnsave.setFont(new java.awt.Font("Calibri", 0, 12));
        btnsave.setText("Save");
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
        });
        jPanel1.add(btnsave);
        btnsave.setBounds(90, 460, 80, 24);

        lbldurasi.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbldurasi.setToolTipText("");
        jPanel1.add(lbldurasi);
        lbldurasi.setBounds(190, 480, 120, 20);

        btnopentic.setFont(new java.awt.Font("Calibri", 0, 12));
        btnopentic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tic.jpg"))); // NOI18N
        btnopentic.setText("Open Ticket");
        btnopentic.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnopentic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenticActionPerformed(evt);
            }
        });
        jPanel1.add(btnopentic);
        btnopentic.setBounds(160, 170, 150, 24);

        jLabel37.setBackground(new java.awt.Color(255, 255, 204));
        jLabel37.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel37.setText("Ext.");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(10, 50, 100, 20);

        txtdial2.setFont(new java.awt.Font("Calibri", 0, 12));
        txtdial2.setEnabled(false);
        txtdial2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdial2KeyReleased(evt);
            }
        });
        jPanel1.add(txtdial2);
        txtdial2.setBounds(110, 50, 150, 24);

        jLabel36.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel36.setText("Cust. Company");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(10, 110, 100, 20);

        cbcust.setFont(new java.awt.Font("Calibri", 0, 12));
        cbcust.setMaximumRowCount(9);
        cbcust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        jPanel1.add(cbcust);
        cbcust.setBounds(110, 110, 200, 24);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<<TICKET REFERENCE>>", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Calibri", 0, 11));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ticket No. :"); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(220, 20, 100, 20);

        txtnotic.setEditable(false);
        txtnotic.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel2.add(txtnotic);
        txtnotic.setBounds(320, 20, 160, 24);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel5.setText("Category :"); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 40, 100, 20);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel6.setText("Department :"); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 60, 100, 20);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel7.setText("Prority :"); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 20, 100, 20);

        cbcategory.setFont(new java.awt.Font("Calibri", 0, 12));
        cbcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcategoryActionPerformed(evt);
            }
        });
        cbcategory.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbcategoryFocusLost(evt);
            }
        });
        jPanel2.add(cbcategory);
        cbcategory.setBounds(120, 40, 360, 24);

        cbprior.setFont(new java.awt.Font("Calibri", 0, 12));
        cbprior.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NORMAL", "URGENT" }));
        jPanel2.add(cbprior);
        cbprior.setBounds(120, 20, 100, 24);

        cbdept.setFont(new java.awt.Font("Calibri", 0, 12));
        cbdept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbdeptMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbdeptMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbdeptMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbdeptMouseReleased(evt);
            }
        });
        cbdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdeptActionPerformed(evt);
            }
        });
        cbdept.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbdeptFocusLost(evt);
            }
        });
        jPanel2.add(cbdept);
        cbdept.setBounds(120, 60, 360, 24);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel8.setText("Details :"); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 340, 100, 20);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel9.setText("Solution :"); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 450, 100, 20);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Calibri", 0, 12));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(null);

        jLabel22.setBackground(new java.awt.Color(102, 102, 255));
        jLabel22.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel22.setText("Contract No."); // NOI18N
        jPanel5.add(jLabel22);
        jLabel22.setBounds(10, 10, 100, 20);

        txtcontract.setFont(new java.awt.Font("Calibri", 0, 12));
        txtcontract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontractActionPerformed(evt);
            }
        });
        jPanel5.add(txtcontract);
        txtcontract.setBounds(110, 10, 360, 24);

        jLabel23.setBackground(new java.awt.Color(102, 102, 255));
        jLabel23.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel23.setText("Cust. Code"); // NOI18N
        jPanel5.add(jLabel23);
        jLabel23.setBounds(10, 30, 100, 20);

        txtcuscod.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel5.add(txtcuscod);
        txtcuscod.setBounds(110, 30, 360, 24);

        txtcusnam.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel5.add(txtcusnam);
        txtcusnam.setBounds(110, 50, 360, 24);

        jLabel10.setBackground(new java.awt.Color(102, 102, 255));
        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel10.setText("Cust. Name :"); // NOI18N
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 50, 100, 20);

        jLabel11.setBackground(new java.awt.Color(102, 102, 255));
        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cust.Fax :"); // NOI18N
        jPanel5.add(jLabel11);
        jLabel11.setBounds(240, 70, 100, 20);

        txtcusfax.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel5.add(txtcusfax);
        txtcusfax.setBounds(340, 70, 130, 24);

        jLabel12.setBackground(new java.awt.Color(102, 102, 255));
        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel12.setText("Cust. Phone :"); // NOI18N
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 70, 100, 20);

        txtcuspho.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel5.add(txtcuspho);
        txtcuspho.setBounds(110, 70, 130, 24);

        jLabel21.setBackground(new java.awt.Color(102, 102, 255));
        jLabel21.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel21.setText("Cust address:"); // NOI18N
        jPanel5.add(jLabel21);
        jLabel21.setBounds(10, 90, 100, 20);

        txtcustadd.setColumns(20);
        txtcustadd.setFont(new java.awt.Font("Calibri", 0, 12));
        txtcustadd.setLineWrap(true);
        txtcustadd.setRows(5);
        jScrollPane6.setViewportView(txtcustadd);

        jPanel5.add(jScrollPane6);
        jScrollPane6.setBounds(110, 90, 360, 70);

        jLabel13.setBackground(new java.awt.Color(102, 102, 255));
        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel13.setText("Cust. PIC :"); // NOI18N
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 160, 100, 20);

        txtcuspic.setFont(new java.awt.Font("Calibri", 0, 12));
        txtcuspic.setAutoscrolls(false);
        jPanel5.add(txtcuspic);
        txtcuspic.setBounds(110, 160, 360, 24);

        jLabel24.setBackground(new java.awt.Color(102, 102, 255));
        jLabel24.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel24.setText("Contract Start"); // NOI18N
        jPanel5.add(jLabel24);
        jLabel24.setBounds(10, 180, 100, 20);

        txtcusconst.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel5.add(txtcusconst);
        txtcusconst.setBounds(110, 180, 130, 24);

        jLabel25.setBackground(new java.awt.Color(102, 102, 255));
        jLabel25.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Contact End :"); // NOI18N
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel25);
        jLabel25.setBounds(240, 180, 100, 20);

        txtcusconend.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel5.add(txtcusconend);
        txtcusconend.setBounds(340, 180, 130, 24);

        btnsrchcus1.setFont(new java.awt.Font("Calibri", 0, 11));
        btnsrchcus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1245117595_001_37.png"))); // NOI18N
        btnsrchcus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsrchcus1MouseClicked(evt);
            }
        });
        jPanel5.add(btnsrchcus1);
        btnsrchcus1.setBounds(450, 200, 20, 24);

        jLabel31.setBackground(new java.awt.Color(102, 102, 255));
        jLabel31.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel31.setText("Start Date"); // NOI18N
        jPanel5.add(jLabel31);
        jLabel31.setBounds(10, 200, 100, 20);

        txtcusconst1.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel5.add(txtcusconst1);
        txtcusconst1.setBounds(110, 200, 130, 24);

        jTabbedPane1.addTab("Customer", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel14.setText("CSO Name :"); // NOI18N
        jPanel6.add(jLabel14);
        jLabel14.setBounds(10, 30, 100, 20);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel15.setText("CSO Phone :"); // NOI18N
        jPanel6.add(jLabel15);
        jLabel15.setBounds(10, 50, 100, 20);

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel26.setText("CC email to :"); // NOI18N
        jPanel6.add(jLabel26);
        jLabel26.setBounds(10, 70, 100, 20);

        txtcsomail.setFont(new java.awt.Font("Calibri", 0, 11));
        txtcsomail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcsomailActionPerformed(evt);
            }
        });
        jPanel6.add(txtcsomail);
        txtcsomail.setBounds(110, 70, 360, 24);

        txtcsopho.setFont(new java.awt.Font("Calibri", 0, 11));
        jPanel6.add(txtcsopho);
        txtcsopho.setBounds(110, 50, 360, 24);

        txtcso.setFont(new java.awt.Font("Calibri", 0, 11));
        txtcso.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtcsoCaretUpdate(evt);
            }
        });
        txtcso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcsoActionPerformed(evt);
            }
        });
        jPanel6.add(txtcso);
        txtcso.setBounds(110, 30, 360, 24);

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel27.setText("CSO Code :"); // NOI18N
        jPanel6.add(jLabel27);
        jLabel27.setBounds(10, 10, 100, 20);

        txtcsocode.setFont(new java.awt.Font("Calibri", 0, 11));
        txtcsocode.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtcsocodeCaretUpdate(evt);
            }
        });
        txtcsocode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcsocodeActionPerformed(evt);
            }
        });
        jPanel6.add(txtcsocode);
        txtcsocode.setBounds(110, 10, 360, 24);

        jTabbedPane1.addTab("CSO", jPanel6);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel11.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel16.setText("User Name :"); // NOI18N
        jPanel11.add(jLabel16);
        jLabel16.setBounds(10, 10, 100, 20);

        txtusr.setFont(new java.awt.Font("Calibri", 0, 11));
        jPanel11.add(txtusr);
        txtusr.setBounds(110, 10, 360, 24);
        txtusr.getText().toUpperCase();

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel17.setText("User Address :"); // NOI18N
        jPanel11.add(jLabel17);
        jLabel17.setBounds(10, 50, 100, 20);

        txtusrpho.setFont(new java.awt.Font("Calibri", 0, 11));
        jPanel11.add(txtusrpho);
        txtusrpho.setBounds(110, 30, 360, 24);

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel28.setText("User Phone :"); // NOI18N
        jPanel11.add(jLabel28);
        jLabel28.setBounds(10, 30, 100, 20);

        txtusraddr.setColumns(20);
        txtusraddr.setRows(5);
        jScrollPane7.setViewportView(txtusraddr);

        jPanel11.add(jScrollPane7);
        jScrollPane7.setBounds(110, 50, 360, 96);

        jTabbedPane1.addTab("User", jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel12.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel18.setText("No. Plat :"); // NOI18N
        jPanel12.add(jLabel18);
        jLabel18.setBounds(10, 10, 100, 20);

        cbnoplat.setFont(new java.awt.Font("Calibri", 0, 11));
        cbnoplat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbnoplatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbnoplatFocusLost(evt);
            }
        });
        cbnoplat.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                cbnoplatCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel12.add(cbnoplat);
        cbnoplat.setBounds(110, 10, 100, 24);

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel19.setText("Jenis :"); // NOI18N
        jPanel12.add(jLabel19);
        jLabel19.setBounds(10, 30, 100, 20);

        txtjenis.setFont(new java.awt.Font("Calibri", 0, 11));
        jPanel12.add(txtjenis);
        txtjenis.setBounds(110, 30, 360, 24);

        jLabel29.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel29.setText("Color  :"); // NOI18N
        jPanel12.add(jLabel29);
        jLabel29.setBounds(10, 70, 100, 20);

        txtwarna.setFont(new java.awt.Font("Calibri", 0, 11));
        jPanel12.add(txtwarna);
        txtwarna.setBounds(110, 70, 360, 24);

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel30.setText("Type :"); // NOI18N
        jPanel12.add(jLabel30);
        jLabel30.setBounds(10, 50, 100, 20);

        txttype.setFont(new java.awt.Font("Calibri", 0, 11));
        jPanel12.add(txttype);
        txttype.setBounds(110, 50, 360, 24);

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel32.setText("Year :"); // NOI18N
        jPanel12.add(jLabel32);
        jLabel32.setBounds(10, 90, 100, 20);

        txtthn.setFont(new java.awt.Font("Calibri", 0, 11));
        jPanel12.add(txtthn);
        txtthn.setBounds(110, 90, 360, 24);

        jTabbedPane1.addTab("Vehicle", jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel13.setLayout(null);

        jLabel33.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel33.setText("Driver Code :"); // NOI18N
        jPanel13.add(jLabel33);
        jLabel33.setBounds(10, 10, 100, 20);

        jLabel34.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel34.setText("Driver Name :"); // NOI18N
        jPanel13.add(jLabel34);
        jLabel34.setBounds(10, 30, 100, 20);

        txtdrinm.setFont(new java.awt.Font("Calibri", 0, 11));
        jPanel13.add(txtdrinm);
        txtdrinm.setBounds(110, 30, 360, 24);

        cbdriver.setFont(new java.awt.Font("Calibri", 0, 11));
        cbdriver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbdriverFocusGained(evt);
            }
        });
        jPanel13.add(cbdriver);
        cbdriver.setBounds(110, 10, 100, 24);

        jLabel35.setFont(new java.awt.Font("Calibri", 0, 11));
        jLabel35.setText("Driver Phone :"); // NOI18N
        jPanel13.add(jLabel35);
        jLabel35.setBounds(10, 50, 100, 20);

        txtdripho1.setFont(new java.awt.Font("Calibri", 0, 11));
        jPanel13.add(txtdripho1);
        txtdripho1.setBounds(110, 50, 360, 24);

        jTabbedPane1.addTab("Driver", jPanel13);

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 80, 492, 260);

        txtdetails.setColumns(20);
        txtdetails.setEditable(false);
        txtdetails.setFont(new java.awt.Font("Calibri", 0, 12));
        txtdetails.setLineWrap(true);
        txtdetails.setRows(5);
        jScrollPane1.setViewportView(txtdetails);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(120, 342, 380, 100);

        txtsolution.setColumns(20);
        txtsolution.setEditable(false);
        txtsolution.setFont(new java.awt.Font("Calibri", 0, 12));
        txtsolution.setLineWrap(true);
        txtsolution.setRows(5);
        jScrollPane8.setViewportView(txtsolution);

        jPanel2.add(jScrollPane8);
        jScrollPane8.setBounds(120, 450, 380, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        // TODO add your handling code here:
        if(xxx==0){
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Data Incomplete, Please fill Date and time first");
        }
}//GEN-LAST:event_btncloseMouseClicked

    private void btnsrchcusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsrchcusMouseClicked
        // TODO add your handling code here:
        Search_ticket st = new Search_ticket();
        st.setVisible(true);
        Sct.out=true;
}//GEN-LAST:event_btnsrchcusMouseClicked

    private void txtnotic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnotic1MouseClicked
        // TODO add your handling code here:
        try{
           sql="select a.ticket_no, a._priority, a.category, b.dept_name, a.assign_dept, a.user, a.user_phone, a.vehicle_platno, a.vehicle_type, a.vehicle_warna, a.driver_name, a.driver_phone, a.cust_name, a.cust_phone, a.cust_pic, a.cust_pic_phone, a.cso_name, a.cso_phone, a.details, a.solution from tickets a, _department b where a.dept_id=b.dept_id and a.ticket_id='"+txtnotic1.getText()+"' ";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                txtnotic.setText(rs.getString(1));
                cbcategory.addItem(rs.getString(3));
                cbprior.setSelectedIndex(Integer.parseInt(rs.getString(2)));
                cbdept.addItem(rs.getString(4));
//                cbasdept.setSelectedItem(rs.getString(5));
                txtusr.setText(rs.getString(6));
                txtusrpho.setText(rs.getString(7));
                cbnoplat.addItem(rs.getString(8));
                txttype.setText(rs.getString(9));
                txtwarna.setText(rs.getString(10));
                cbdriver.addItem(rs.getString(11));
                txtdripho1.setText(rs.getString(12));
                txtcusnam.setText(rs.getString(13));
                txtcuspho.setText(rs.getString(14));
                txtcuspic.setText(rs.getString(15));
//                txtpicpho.setText(rs.getString(16));
                txtcso.setText(rs.getString(17));
                txtcsopho.setText(rs.getString(18));
                txtdetails.setText(rs.getString(19));
//                txtsolution.setText(rs.getString(12));
//                txtsolutionclos.setText(rs.getString(12));
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtnotic1MouseClicked

    private void btnhangupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhangupMouseClicked
        // TODO add your handling code here:
       
}//GEN-LAST:event_btnhangupMouseClicked

    private void txtnotic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotic1ActionPerformed
        // TODO add your handling code here:
        if (txtnotic1.getText().equals("")){
            
        }else{
            klik2();
        }
    }//GEN-LAST:event_txtnotic1ActionPerformed

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
        // TODO add your handling code here:
        if(call==true){
            zz=loid;
        }
        if(txtnotic1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ticket No cannot be empty", "VALIDATION",JOptionPane.WARNING_MESSAGE);
        }else{
            if(ckconf.isSelected()==true){
                conf=2;
            }else{
                conf=1;
            }
            if(cbcust.getSelectedIndex()!=-1){
                sql = "update log_phone set " +
                    "comment='"+txtcomment.getText()+"' , cust_name='"+cbcust.getSelectedItem()+"'" +
                    ", ticket_id='"+oid+"' " +
                    "where log_id='"+loid+"'";
                CCanj.jconn.SQLExecute(sql, CCanj.conn);
            }else{
                JOptionPane.showMessageDialog(null, "Please input the Customer Company");
            }
        }
        
        
}//GEN-LAST:event_btnsaveMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        stt();
        if(call==true){
            if(obtic==true){
                if (status==0 && asdep==0){
                    sql="update tickets set _status=1, process_date='"+opdt+"', process_time='"+optm+"', process_username='"+CCanj.lbluser.getText()+"' where ticket_id='"+Tic.id+"' and ticket_no='"+txtnotic.getText()+"'";
                    CCanj.jconn.SQLExecute(sql,CCanj.conn);
                    System.out.print(sql);
                    status=1;
                }
                sql1="insert into log_tickets (log_date,log_time,username,user_level,ticket_id,_status,info,ticket_no) values ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+usrlvl+"','"+txtnotic1.getText()+"','"+status+"','Outgoing Call \nDial Number : "+txtdial.getText()+"\nDial Name : "+txtdialnm.getText()+"\nCaller type : "+cbcaltype.getSelectedItem()+" \n\n "+txtcomment.getText()+"','"+txtnotic.getText()+"')";
                CCanj.jconn.SQLExecute(sql1, CCanj.conn);
                try{
                    sql2="select note from tickets where ticket_id='"+Tic.id+"'";
                    rs = CCanj.jconn.SQLExecuteRS(sql2, CCanj.conn);
                    while(rs.next()){
                        solution=rs.getString(1);
                    }
                }catch(Exception exc){
                    System.err.println(exc.getMessage());
                }
                sql3="update tickets set note='"+CCanj.lbluser.getText()+"@"+opdt.substring(8, 10) + "/" + opdt.substring(5, 7) + "/" + opdt.substring(0, 4)+"\n"+optm.replaceAll(":",".")+"\nOutgoing Call \nDial Number : "+txtdial.getText()+"\nDial Name : "+txtdialnm.getText()+"\nCaller type : "+cbcaltype.getSelectedItem()+" \n\n "+txtcomment.getText()+"\n===' where ticket_id='"+Tic.id+"'";
                CCanj.jconn.SQLExecute(sql3,CCanj.conn);
            }
            zz=loid;
        }        
        if(ckconf.isSelected()==true){
                conf=2;
            }else{
                conf=1;
            }

            if(zz==null){
                sql = "update tickets set " +
                        "confirmed='"+conf+"' " +
                        "where ticket_id='"+oid+"'";
                CCanj.jconn.SQLExecute(sql, CCanj.conn);

            }else{
                sql = "update tickets set " +
                    "confirmed='"+conf+"' " +
                    ", logphone_id='"+zz+"' " +
                    "where ticket_id='"+oid+"'";
                CCanj.jconn.SQLExecute(sql, CCanj.conn);
//                JOptionPane.showMessageDialog(null, "UPDATE, TICKET HAS CONFIRMED ", "TICKETING",JOptionPane.WARNING_MESSAGE);
            }
        CCanj.call();
        call=false;
        btncall.setEnabled(true);
//        try {
//            conn.close();
//        } catch (SQLException ex) {
//            System.err.println(ex.getMessage());
//        }
    }//GEN-LAST:event_formWindowClosed

    private void ckconfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckconfMouseClicked
        // TODO add your handling code here:
         if(ckconf.isSelected()==true){
                conf=2;
            }else{
                conf=1;
            }
    }//GEN-LAST:event_ckconfMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.out.print(xxx);
        if(xxx==0){
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Data Incomplete, Please fill Date and time first");
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtdialnmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdialnmFocusLost
        // TODO add your handling code here:
        if(!txtdialnm.getText().equals("")){
            btnhangup.setEnabled(true);
        }
    }//GEN-LAST:event_txtdialnmFocusLost

    private void cbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcategoryActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cbcategoryActionPerformed

    private void cbcategoryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbcategoryFocusLost
        // TODO add your handling code here:
        if(cbcategory.getSelectedItem().equals("--")){
//            showDept();
        }else{
            try{
                cbdept.removeAllItems();
                sql="select a.dept_name from _department a, _ticketcategory b where a.dept_id=b.dept_id and b.category_name='"+cbcategory.getSelectedItem()+"'";
                rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
                while(rs.next()){
                    cbdept.addItem(rs.getString(1));
                }cbdept.addItem("--");
            }catch(Exception e){
                System.out.println(e);

            }
        }
}//GEN-LAST:event_cbcategoryFocusLost

    private void cbdeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbdeptMouseClicked
        // TODO add your handling code here:
        //        showcategory();
}//GEN-LAST:event_cbdeptMouseClicked

    private void cbdeptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbdeptMouseExited
        // TODO add your handling code here:
        //        showcategory();
}//GEN-LAST:event_cbdeptMouseExited

    private void cbdeptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbdeptMousePressed
        // TODO add your handling code here:
        //        showcategory();
}//GEN-LAST:event_cbdeptMousePressed

    private void cbdeptMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbdeptMouseReleased
        // TODO add your handling code here:
        //        showcategory();
}//GEN-LAST:event_cbdeptMouseReleased

    private void cbdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdeptActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cbdeptActionPerformed

    private void cbdeptFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbdeptFocusLost
        // TODO add your handling code here:
        if(cbdept.getSelectedItem().equals("--")){
//            showcategory();
        }else{
            if (cbcategory.getSelectedItem().equals("--")){
                try{
                    cbcategory.removeAllItems();
                    sql="select a.category_name from _ticketcategory a, _department b where a.dept_id=b.dept_id and b.dept_name='"+cbdept.getSelectedItem()+"'";
                    rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
                    while(rs.next()){
                        cbcategory.addItem(rs.getString(1));
                    }

                }catch(Exception e){
                    System.out.println(e);
                }
            }

        }
}//GEN-LAST:event_cbdeptFocusLost

    private void txtcontractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontractActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtcontractActionPerformed

    private void btnsrchcus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsrchcus1MouseClicked
        // TODO add your handling code here:
        Search_customer sc = new Search_customer();
        sc.setVisible(true);
}//GEN-LAST:event_btnsrchcus1MouseClicked

    private void txtcsomailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcsomailActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtcsomailActionPerformed

    private void txtcsoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtcsoCaretUpdate
        // TODO add your handling code here:
        //        if (txtcso.getText().equals("")){
        //            txtcsomail.setText("hendri.suhenda@jsm.co.id");
        //        }else {
        //            txtcsomail.setText("marshal@jsm.co.id");
        //        }
}//GEN-LAST:event_txtcsoCaretUpdate

    private void txtcsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcsoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtcsoActionPerformed

    private void txtcsocodeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtcsocodeCaretUpdate
        // TODO add your handling code here:
}//GEN-LAST:event_txtcsocodeCaretUpdate

    private void txtcsocodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcsocodeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtcsocodeActionPerformed

    private void cbnoplatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbnoplatFocusGained
        // TODO add your handling code here:
        try{
            sql="select vehicle_type, vehicle_warna from customer_order where vehicle_platno='"+cbnoplat.getSelectedItem()+"' and cust_name='"+txtcusnam.getText()+"'";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                txtjenis.setText(rs.getString(1));
                txtwarna.setText(rs.getString(2));
            }
        }catch(Exception e){
            System.out.println(e);
        }

        //        if(cbtype.getSelectedItem().equals("--")||cbwarna.getSelectedItem().equals("--")){
        //            if(cbtype.getSelectedItem().equals("--")||cbwarna.getSelectedItem().equals("--")||cbdriver.getSelectedItem().equals("--")){
        //
        //            }else{
        //                try{
        //                    cbnoplat.removeAllItems();
        //                    sql="select vehicle_platno from customer_order where vehicle_type='"+cbtype.getSelectedItem()+"' and vehilce_warna='"+cbwarna.getSelectedItem()+"' and driver_name='"+cbdriver.getSelectedItem()+"'";
        //                    rs=jconn.SQLExecuteRS(sql,conn);
        //                while(rs.next()){
        //                    cbtype.addItem(rs.getString(1));
        //                }
        //                }catch(Exception e){
        //                    System.out.println(e);
        //                 }
        //            }
        //        }else{
        //             try{
        //            cbnoplat.removeAllItems();
        //            sql="select vehicle_platno from customer_order where vehicle_type='"+cbtype.getSelectedItem()+"' and vehicle_warna='"+cbwarna.getSelectedItem()+"'";
        //            rs=jconn.SQLExecuteRS(sql,conn);
        //            while(rs.next()){
        //                cbtype.addItem(rs.getString(1));
        //            }
        //        }catch(Exception e){
        //            System.out.println(e);
        //
        //        }
        //        }
}//GEN-LAST:event_cbnoplatFocusGained

    private void cbnoplatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbnoplatFocusLost
        // TODO add your handling code here:
        //            showWarna();
        //        if(cbnoplat.getSelectedItem().equals("--")){
        //            showType();
        //            showWarna();
        //        }
}//GEN-LAST:event_cbnoplatFocusLost

    private void cbnoplatCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cbnoplatCaretPositionChanged
        // TODO add your handling code here:
        try{
            sql="select vehicle_type, vehicle_warna from customer_order where vehicle_platno='"+cbnoplat.getSelectedItem()+"' and cust_name='"+txtcusnam.getText()+"'";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                txtjenis.setText(rs.getString(1));
                txtwarna.setText(rs.getString(2));
            }
        }catch(Exception e){
            System.out.println(e);
        }
}//GEN-LAST:event_cbnoplatCaretPositionChanged

    private void cbdriverFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbdriverFocusGained
        // TODO add your handling code here:
        //        if(cbnoplat.getSelectedItem().equals("--") && cbtype.getSelectedItem().equals("--") && cbwarna.getSelectedItem().equals("--")){
        //
        //        }else{
        //            try{
        //            cbdriver.removeAllItems();
        //            sql="select driver_name from customer_order where vehicle_platno='"+cbnoplat.getSelectedItem()+"' and driver_name is not null GROUP BY driver_name";
        //            rs=jconn.SQLExecuteRS(sql,conn);
        //            while(rs.next()){
        //                cbdriver.addItem(rs.getString(1));
        //            }
        //            cbdriver.addItem("--");
        //            }catch(Exception e){
        //                System.out.println(e);
        //            }
        //        }
        //            if(cbdriver.getSelectedItem().equals("--")){
        //            }
}//GEN-LAST:event_cbdriverFocusGained

    private void btnopenticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenticActionPerformed
        // TODO add your handling code here:
        ticket tic=new ticket();
        tic.setVisible(true);

        Tic.caltic=true;
        Tic.newtic=true;
}//GEN-LAST:event_btnopenticActionPerformed

    private void cbcaltypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcaltypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcaltypeActionPerformed

    private void btnhangupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangupActionPerformed
        // TODO add your handling code here:
        if(!txtdialnm.getText().equals("")){
        optm();
        opdt();
        String tgl=optm.replace(':','.');
        String notic=txtnotic.getText();
        String nmfl=""+opdt+" OUT "+CCanj.lbluser.getText()+" "+tgl+" "+txtdialnm.getText()+".wav";
//        String nmfl="[JSM] "+opdt+" OUT "+CCanj.lbluser.getText()+" "+tgl+" "+txtdialnm.getText()+".wav";

        ti.stop();
            CCanj.s = "HANGUP|"+nmfl+"\r\n";
            CCanj.kirimTele();
            sql="update log_phone set caller_name='"+txtdialnm.getText()+"', ticket_id='"+txtnotic1.getText()+"', caller_type='"+cbcaltype.getSelectedItem()+"', comment='"+txtcomment.getText()+"', duration='"+lbldurasi.getText()+"', filename='"+nmfl+"' where log_id='"+loid+"'";
            CCanj.jconn.SQLExecute(sql, CCanj.conn);
            sql1="update user_account set _activity=1, time_activity=CURRENT_TIMESTAMP where username= '" +CCanj.lbluser.getText()+ "' limit 1";
            CCanj.jconn.SQLExecute(sql1, CCanj.conn);
            JOptionPane.showMessageDialog(null, "CALL DISCONNECTED", "OUTGOING CALL",JOptionPane.WARNING_MESSAGE);

            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(InBoundCall.class.getName()).log(Level.SEVERE, null, ex);
            }
//                  s = "UPLOAD|RECORDING|"+nmfl+"|192.168.0.32|anj\r\n";
                  CCanj.s = "UPLOAD|RECORDING|"+nmfl+"|"+Log.ftpserverRec+"|"+Log.ftpuserRec+"\r\n";
                  CCanj.kirimUplo();
                  xxx=0;
//                  System.out.print(xxx);
                  JOptionPane.showMessageDialog(null, "OUTBOUND RECORDING "+nmfl+" Has been uploaded", "OUTGOING CALL",JOptionPane.WARNING_MESSAGE);
                  CCanj.lblactivity.setText("Registered");
                  btnhangup.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Call Name cannot be empty", "INCOMING CALL",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnhangupActionPerformed

    private void btncallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncallActionPerformed
        // TODO add your handling code here:
        dataregis();
        optm();
        opdt();
        cek();
        CCanj.s = "REGISTER|"+pabx+"|"+out_ext+"|"+out_ext+"\r\n";
        CCanj.kirimTele();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(OutBound.class.getName()).log(Level.SEVERE, null, ex);
        }
        CCanj.s = "DIAL|"+txtdial.getText()+"\r\n";
        CCanj.kirimTele();
        JOptionPane.showMessageDialog(null, "CALLING \n"+txtdial.getText(), "OUTGOING CALL",JOptionPane.WARNING_MESSAGE);
        sql="insert into log_phone (log_date,log_time,username,shift,host_addr,line_number,_direction,phone_number,ticket_id) values ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+Log.cbshift.getSelectedIndex()+"','"+CCanj.pabx+"','"+CCanj.out_ext+"',1,'"+txtdial.getText()+"','"+txtnotic1.getText()+"')";
        CCanj.jconn.SQLExecute(sql, CCanj.conn);

                      sqlid="select distinct last_insert_id() from log_phone";
                      rs=CCanj.jconn.SQLExecuteRS(sqlid, CCanj.conn);
                        try {
                            while (rs.next()) {
                                loid = rs.getString(1);
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(OutBound.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
        sql1="update user_account set _activity=3, time_activity=CURRENT_TIMESTAMP where username= '" +CCanj.lbluser.getText()+ "' limit 1";
        CCanj.jconn.SQLExecute(sql1, CCanj.conn);
        
        call=true;
        CCanj.lblactivity.setText("On line");
        btncall.setEnabled(false);
        txtdial2.setEnabled(true);
    }//GEN-LAST:event_btncallActionPerformed
String digit,s,ext,delete;
int d,index,last,del;
    private void txtdial2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdial2KeyReleased
        // TODO add your handling code here:
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(OutBound.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (evt.getKeyChar()>=48 && evt.getKeyChar()<=57 || evt.getKeyChar()==8){
            ext=","+txtdial2.getText();
            d=ext.length();
            digit=ext.substring(d-1, d);
            if(d>=2 && evt.getKeyChar()!=8){
                CCanj.s = "DTMF|"+digit+"\r\n";
                CCanj.kirimTele();
            }
        }else{
            ext=","+txtdial2.getText();
            del=ext.length();
            if (del>=1){
                ext=ext.substring(1,del-1);
                txtdial2.setText(ext);
            }
            JOptionPane.showMessageDialog(null, "Character Number Only", "validation",JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_txtdial2KeyReleased

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutBound().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncall;
    private javax.swing.JButton btnclose;
    public static javax.swing.JButton btnhangup;
    private javax.swing.JButton btnopentic;
    public static javax.swing.JButton btnsave;
    private javax.swing.JButton btnsrchcus;
    private javax.swing.JButton btnsrchcus1;
    public static javax.swing.JComboBox cbcaltype;
    public static javax.swing.JComboBox cbcategory;
    public static javax.swing.JComboBox cbcust;
    public static javax.swing.JComboBox cbdept;
    public static javax.swing.JComboBox cbdriver;
    public static javax.swing.JComboBox cbnoplat;
    public static javax.swing.JComboBox cbprior;
    public static javax.swing.JCheckBox ckconf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JLabel lbldurasi;
    public static javax.swing.JTextArea txtcomment;
    public static javax.swing.JTextField txtcontract;
    public static javax.swing.JTextField txtcso;
    public static javax.swing.JTextField txtcsocode;
    public static javax.swing.JTextField txtcsomail;
    public static javax.swing.JTextField txtcsopho;
    public static javax.swing.JTextField txtcuscod;
    public static javax.swing.JTextField txtcusconend;
    public static javax.swing.JTextField txtcusconst;
    public static javax.swing.JTextField txtcusconst1;
    public static javax.swing.JTextField txtcusfax;
    public static javax.swing.JTextField txtcusnam;
    public static javax.swing.JTextField txtcuspho;
    public static javax.swing.JTextField txtcuspic;
    public static javax.swing.JTextArea txtcustadd;
    public static javax.swing.JTextArea txtdetails;
    public static javax.swing.JTextField txtdial;
    public static javax.swing.JTextField txtdial2;
    public static javax.swing.JTextField txtdialnm;
    public static javax.swing.JTextField txtdrinm;
    public static javax.swing.JTextField txtdripho1;
    public static javax.swing.JTextField txtjenis;
    public static javax.swing.JTextField txtnotic;
    public static javax.swing.JTextField txtnotic1;
    public static javax.swing.JTextArea txtsolution;
    public static javax.swing.JTextField txtthn;
    public static javax.swing.JTextField txttype;
    public static javax.swing.JTextField txtusr;
    public static javax.swing.JTextArea txtusraddr;
    public static javax.swing.JTextField txtusrpho;
    public static javax.swing.JTextField txtwarna;
    // End of variables declaration//GEN-END:variables

    public static String sql;
    public static String sql1;
    public static String sql2;
    public static String sql3;
    public static String sqlid;
    public static ResultSet rs;
//    public static JavaConnector jconn=new JavaConnector();
//    public static Connection conn;

    public static void cek(){

         if (lbldurasi.getText().equals("")){
             System.out.print("Proses cek durasi");
            start();
             System.out.print("start timer");
            ti= new Timer(1000, duration);
            ti.start();
            xxx=1;

        }
    }
       
        private void opdt(){
          try{
              sql="select CURRENT_DATE";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  opdt=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
    }
        private void optm(){
            try{
              sql="select CURRENT_TIME";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  optm=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
        }
        public static void klik2(){
//                 try{
//            sql="select a.ticket_no, a._priority, a.category, b.dept_name, a.assign_dept, a.user, a.user_phone, a.vehicle_platno, a.vehicle_type, a.vehicle_warna, a.driver_name, a.driver_phone, a.cust_name, a.cust_phone, a.cust_pic, a.cust_pic_phone, a.cso_name, a.cso_phone, a.details, a.solution from tickets a, _department b where a.dept_id=b.dept_id and a.ticket_no='"+txtnotic.getText()+"' ";
                  try{
            sql="select a.ticket_id," +
                    " a.ticket_no, " +
                    " a._priority, " +
                    "a.category, " +
                    "b.dept_name, " +
                    "a.assign_dept, " +
                    "a.vehicle_platno, " +
                    "a.vehicle_jenis, " +
                    "a.vehicle_type, " +
                    "a.vehicle_tahun, " +
                    "a.vehicle_warna, " +
                    "a.driver_code, " +
                    "a.driver_name, " +
                    "a.driver_phone, " +
                    "a.cust_code, " +
                    "a.cust_name, " +
                    "a.cust_address, " +
                    "a.cust_phone, " +
                    "a.cust_fax, " +
                    "a.cust_pic, " +
                    "a.contract_no, " +
                    "a.contract_startdate, " +
                    "a.contract_enddate, " +
                    "a.startdate, " +
                    "a.user, " +
                    "a.user_phone, " +
                    "a.user_address, " +
                    "a.cso_code, " +
                    "a.cso_name, " +
                    "a.cso_phone, " +//18
                    "a.cso_mail, " +
                    "a.details, " +//19
                    "a.solution, " +
                    "a._submitted, " +//21
                    "a.cso_mail, " +
                    "a.confirmed " +
                    "from tickets a, _department b " +
                    "where a.dept_id=b.dept_id and a.ticket_no='"+txtnotic.getText()+"' ";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);

//                 System.out.println(sql);
            while(rs.next()){
                txtnotic1.setText(rs.getString("ticket_id"));
                oid=Integer.parseInt(rs.getString("ticket_id"));
                cbcategory.addItem(rs.getString("category"));
                cbprior.setSelectedIndex(Integer.parseInt(rs.getString("_priority")));
                cbdept.addItem(rs.getString("dept_name"));
//                cbasdept.setSelectedItem(rs.getString(5));
                txtusr.setText(rs.getString("user"));
                txtusrpho.setText(rs.getString("user_phone"));
                txtusraddr.setText(rs.getString("user_address"));
                cbnoplat.addItem(rs.getString("vehicle_platno"));
                txtjenis.setText(rs.getString("vehicle_jenis"));
                txttype.setText(rs.getString("vehicle_type"));
                txtwarna.setText(rs.getString("vehicle_warna"));
                txtthn.setText(rs.getString("vehicle_tahun"));
                cbdriver.addItem(rs.getString("driver_code"));
                txtdrinm.setText(rs.getString("driver_name"));
                txtdripho1.setText(rs.getString("driver_phone"));
                txtcuscod.setText(rs.getString("cust_code"));
                txtcusnam.setText(rs.getString("cust_name"));
                txtcusfax.setText(rs.getString("cust_fax"));
                txtcuspho.setText(rs.getString("cust_phone"));
                txtcuspic.setText(rs.getString("cust_pic"));
                txtcontract.setText(rs.getString("contract_no"));
                txtcusconst.setText(rs.getString("contract_startdate"));
                txtcusconst1.setText(rs.getString("startdate"));
                txtcusconend.setText(rs.getString("contract_enddate"));
                txtcustadd.setText(rs.getString("cust_address"));
                txtcsocode.setText(rs.getString("cso_code"));
                txtcso.setText(rs.getString("cso_name"));
                txtcsopho.setText(rs.getString("cso_phone"));
                txtcsomail.setText(rs.getString("cso_mail"));
                txtdetails.setText(rs.getString("details"));
                submit=Integer.parseInt(rs.getString("_submitted"));
                txtsolution.setText(rs.getString("solution"));
                conf=Integer.parseInt(rs.getString("confirmed"));
//            System.out.println("jalan klik 2");
            }
        }catch(Exception e){
            System.out.println(e);

        }
      if(conf==2){
          ckconf.setSelected(true);
      }else{
          ckconf.setSelected(false);
      }

      }
        public static void open(){
        sql = "select a.*, b.dept_name from tickets a, _department b " +
                    "where confirmed=1 " +
                    "and a.dept_id=b.dept_id " +
                    "and confirm_username='"+ CCanj.lbluser.getText()+"'";
            rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
            System.out.print("\ndebug open outbound : "+sql+"\n");
        try {
            while (rs.next()) {
                z++;
                System.out.print("\nisi result set) : "+rs+"\n");

                System.out.print("\nrs.getString(0) : "+rs.getString(1)+"\n");
                System.out.print("\nrs.getString(1) : "+rs.getString(1)+"\n");
                oid=Integer.parseInt(rs.getString("ticket_id"));
                txtnotic1.setText(rs.getString("ticket_no"));
                cbcategory.addItem(rs.getString("category"));
                cbprior.setSelectedIndex(Integer.parseInt(rs.getString("_priority")));
                cbdept.addItem(rs.getString("dept_name"));
//                cbasdept.setSelectedItem(rs.getString(5));
                txtusr.setText(rs.getString("user"));
                txtusrpho.setText(rs.getString("user_phone"));
                txtusraddr.setText(rs.getString("user_address"));
                cbnoplat.addItem(rs.getString("vehicle_platno"));
                txtjenis.setText(rs.getString("vehicle_jenis"));
                txttype.setText(rs.getString("vehicle_type"));
                txtwarna.setText(rs.getString("vehicle_warna"));
                txtthn.setText(rs.getString("vehicle_tahun"));
                cbdriver.addItem(rs.getString("driver_code"));
                txtdrinm.setText(rs.getString("driver_name"));
                txtdripho1.setText(rs.getString("driver_phone"));
                txtcuscod.setText(rs.getString("cust_code"));
                txtcusnam.setText(rs.getString("cust_name"));
                txtcusfax.setText(rs.getString("cust_fax"));
                txtcuspho.setText(rs.getString("cust_phone"));
                txtcuspic.setText(rs.getString("cust_pic"));
                txtcontract.setText(rs.getString("contract_no"));
                txtcusconst.setText(rs.getString("contract_startdate"));
                txtcusconst1.setText(rs.getString("startdate"));
                txtcusconend.setText(rs.getString("contract_enddate"));
                txtcustadd.setText(rs.getString("cust_address"));
                txtcsocode.setText(rs.getString("cso_code"));
                txtcso.setText(rs.getString("cso_name"));
                txtcsopho.setText(rs.getString("cso_phone"));
                txtcsomail.setText(rs.getString("cso_mail"));
                txtdetails.setText(rs.getString("details"));
                submit=Integer.parseInt(rs.getString("_submitted"));
                txtsolution.setText(rs.getString("solution"));
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }
        public static void start() {
        OutBound.startTime = System.currentTimeMillis();
    }


    public static void stop() {
        OutBound.stopTime = System.currentTimeMillis();
    }


    //elaspsed time in seconds
    public static long duration() {
        if (running) {
            elapsed = ((stopTime - startTime) / 1000);
        }
        else {
            elapsed = ((System.currentTimeMillis() - startTime) / 1000);

        long hours = elapsed / 3600,
                remainder = elapsed % 3600,
                minutes = remainder / 60,
                seconds = remainder % 60;

        String ho=(hours<10 ? "0" : "")+hours,
                menit=(minutes<10 ? "0" : "")+minutes,
                detik=(seconds<10 ? "0" : "")+seconds;
        lbldurasi.setText(ho+":"+menit+":"+detik);
        }

        return elapsed;
    }

    public void dataregis(){
          try{
             int row=0;
              sql="select pabx_host, inbound_ext, outbound_ext from user_account where username='"+CCanj.lbluser.getText()+"'";
              rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
//              System.out.println(sql);

            while(rs.next()){
                pabx=rs.getString(1);
                in_ext=rs.getString(2);
                out_ext=rs.getString(3);
            }
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }

    public static Action duration = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                duration();
            }
       };
       private void usrlvl(){
                try{
                    sql="select _level from user_account where username='"+CCanj.lbluser.getText()+"'";
                    rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
                    while(rs.next()){
                        usrlvl=rs.getString(1);
                    }
                }catch(Exception e){
                    System.out.print(e);
                }
            }
       private void stt(){
                try{
                    sql="select _status, assign_dept from tickets where ticket_id='"+Tic.id+"' and ticket_no='"+txtnotic.getText()+"'";
                    rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
                    while(rs.next()){
                        status=Integer.parseInt(rs.getString(1));
                        asdep=Integer.parseInt(rs.getString(2));
                    }
                }catch(Exception e){
                    System.out.print(e);
                }
            }
       private void showCaltype(){
        try{
            cbcaltype.removeAllItems();

            sql="select data from _callertype";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcaltype.addItem(rs.getString(1));
            }
        }catch(Exception e){
            System.out.println(e);

        }
    }
       private void showCust(){
        try{
            cbcust.removeAllItems();
            cbcust.addItem("Others");

            sql="select distinct(cust_name) from customer_order order by cust_name";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcust.addItem(rs.getString(1));
            }
            cbcust.setSelectedIndex(-1);
        }catch(Exception e){
            System.out.println(e);

        }
    }
}
