/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SMS.java
 *
 * Created on Feb 15, 2010, 4:45:48 PM
 */

package cc_tunas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;
import java.awt.Event.*;
import java.sql.*;
import javax.sun.database.JavaConnector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.io.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import java.util.ArrayList;
import java.net.*;

/**
 *
 * @author jsm
 */
public class SMS extends javax.swing.JFrame {

        String in[]=new String[12];
    String ou[]=new String[8];
    String s;
    String optm;
    String opdt;
    int l=160;
    int p=0;
    String limit;
    public static boolean smstic = false;
    public static int id;
    private String tu="";
    int index;

    private String usrlvl, solution;
    public static int status, asdep;
    /** Creates new form SMS */
    public SMS() {
        initComponents();
        setSize(524,269);
        usrlvl();
//        smstic=false;
        limit = txtmsg.getText();
        showCaltype();showCust();
//        p=limit.length();
    }

     private ContactCenterTunas CCanj;
    public SMS(ContactCenterTunas ccanj){
        this();
        this.CCanj=ccanj;
    }
    private ticket Tic;
    public SMS(ticket tic){
        this();
        this.Tic=tic;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtmsg = new javax.swing.JTextArea();
        lbllimit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnsend = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtnotic = new javax.swing.JTextField();
        btnsrchcus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbdraft = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbcaltype = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cbcust = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SMS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(74, 99, 148));
        jTabbedPane1.setFont(new java.awt.Font("Calibri", 0, 12));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel1.setText("draft :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 80, 100, 20);

        txtto.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel1.add(txtto);
        txtto.setBounds(110, 20, 150, 24);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel2.setText("messages :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 60, 100, 20);

        txtmsg.setColumns(20);
        txtmsg.setFont(new java.awt.Font("Calibri", 0, 12));
        txtmsg.setLineWrap(true);
        txtmsg.setRows(5);
        txtmsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtmsgMouseExited(evt);
            }
        });
        txtmsg.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtmsgCaretUpdate(evt);
            }
        });
        txtmsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmsgKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtmsg);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(110, 60, 370, 86);

        lbllimit.setFont(new java.awt.Font("Calibri", 0, 12));
        lbllimit.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbllimit.setText("160");
        jPanel1.add(lbllimit);
        lbllimit.setBounds(360, 40, 18, 20);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel4.setText("Characters Left");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 40, 100, 20);

        btnsend.setFont(new java.awt.Font("Calibri", 0, 11));
        btnsend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sms sent.jpg"))); // NOI18N
        btnsend.setEnabled(false);
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });
        jPanel1.add(btnsend);
        btnsend.setBounds(330, 150, 70, 40);

        btncancel.setFont(new java.awt.Font("Calibri", 0, 11));
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sms canc.jpg"))); // NOI18N
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel);
        btncancel.setBounds(410, 150, 70, 40);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ticket No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 20, 100, 20);

        txtnotic.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel1.add(txtnotic);
        txtnotic.setBounds(360, 20, 100, 24);

        btnsrchcus.setFont(new java.awt.Font("Calibri", 0, 11));
        btnsrchcus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1245117595_001_37.png"))); // NOI18N
        btnsrchcus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsrchcusMouseClicked(evt);
            }
        });
        jPanel1.add(btnsrchcus);
        btnsrchcus.setBounds(460, 20, 20, 20);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel3.setText("to :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 100, 20);

        cbdraft.setFont(new java.awt.Font("Calibri", 0, 12));
        cbdraft.setMaximumRowCount(12);
        cbdraft.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pengiriman storing", "Pengiriman derek", "Keluhan kendaraan (Data tidak lengkap)", "Keluhan kendaraan (Data lengkap)", "Keluhan driver       (Data tidak lengkap)", "Keluhan driver       (Data lengkap)", "Keluhan marketing (Data tidak lengkap)", "Keluhan marketing (Data lengkap)", "Permintaan Data", "Ucapan terima kasih", "Customer minta dihubungi", "Umum" }));
        cbdraft.setSelectedIndex(11);
        cbdraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdraftActionPerformed(evt);
            }
        });
        jPanel1.add(cbdraft);
        cbdraft.setBounds(10, 100, 100, 24);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel6.setText("Direction Type");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 40, 100, 20);

        cbcaltype.setFont(new java.awt.Font("Calibri", 0, 12));
        cbcaltype.setMaximumRowCount(9);
        cbcaltype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        cbcaltype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbcaltypeMouseClicked(evt);
            }
        });
        jPanel1.add(cbcaltype);
        cbcaltype.setBounds(110, 40, 200, 24);

        jLabel7.setFont(jLabel7.getFont().deriveFont((float)11));
        jLabel7.setText("*tambahkan koma (,) jika ingin lebih dari 1 penerima");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 0, 320, 20);

        jLabel36.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel36.setText("Cust. Company");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(10, 150, 100, 20);

        cbcust.setFont(new java.awt.Font("Calibri", 0, 12));
        cbcust.setMaximumRowCount(9);
        cbcust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        jPanel1.add(cbcust);
        cbcust.setBounds(110, 150, 200, 24);

        jTabbedPane1.addTab("Compose", jPanel1);

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 530, 240);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 530, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsrchcusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsrchcusMouseClicked
        // TODO add your handling code here:
        Search_ticket st = new Search_ticket();
        st.setVisible(true);
}//GEN-LAST:event_btnsrchcusMouseClicked

    private void txtmsgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmsgKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()==8){
            if(p<=0){
            }else{
                txtmsg.setEditable(true);
                l+=1;
                p-=1;
                lbllimit.setText(String.valueOf(l));
            }
        }else if (p<=159){
            l--;
            p++;
            lbllimit.setText(String.valueOf(l));
        }else{
            txtmsg.setEditable(false);
        }
    }//GEN-LAST:event_txtmsgKeyTyped

    private void txtmsgCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtmsgCaretUpdate
        // TODO add your handling code here:
        int panjang,t;
        String sms,isi;
        if(txtmsg.getText().length()>=160){
            sms=txtmsg.getText();
            isi=sms.substring(0,159);
            txtmsg.setText((String)isi);
            p=txtmsg.getText().length();
            l=160-p;
            lbllimit.setText(String.valueOf(l));
        }else{
            p=txtmsg.getText().length();
            l=160-p;
            lbllimit.setText(String.valueOf(l));
        }
    }//GEN-LAST:event_txtmsgCaretUpdate

    private void txtmsgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmsgMouseExited
        // TODO add your handling code here:
        int panjang,t;
        String sms,isi;
        if(txtmsg.getText().length()>=160){
            sms=txtmsg.getText();
            isi=sms.substring(0,159);
            txtmsg.setText((String)isi);
            p=txtmsg.getText().length();
            l=160-p;
            lbllimit.setText(String.valueOf(l));
        }else{
            p=txtmsg.getText().length();
            l=160-p;
            lbllimit.setText(String.valueOf(l));
        }
    }//GEN-LAST:event_txtmsgMouseExited

    private void cbdraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdraftActionPerformed
        // TODO add your handling code here:
        if(cbdraft.getSelectedIndex()==0){
            txtmsg.setText("Pelanggan Yth. Kami akan segera mengirimkan mobil service ke lokasi Anda. Mohon kesediaannya untuk menunggu. Tks");
        }
        if(cbdraft.getSelectedIndex()==1){
            txtmsg.setText("Pelanggan Yth. kami akan segera mengirimkan bantuan derek ke lokasi Anda. Mohon kesediaannya untuk menunggu. Tks");
        }
        if(cbdraft.getSelectedIndex()==2){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan kendaraan Anda. Mohon mencantumkan no plat, nama, company, telp, dan, lokasi Anda saat ini. Tks");
        }
        if(cbdraft.getSelectedIndex()==3){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan kendaraan Anda. Mohon kesediaannya untuk menunggu. Tks");
        }
        if(cbdraft.getSelectedIndex()==4){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan tentang driver Anda. Mohon menginformasikan nama driver Anda. Tks");
        }
        if(cbdraft.getSelectedIndex()==5){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan tentang driver Anda. Mohon informasikan kapan kami dapat memanggil driver untuk klarifikasi. Tks");
        }
        if(cbdraft.getSelectedIndex()==6){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan/permintaan Anda. Mohon menginformasikan no plat, nama, company dan, telp Anda. Tks");
        }
        if(cbdraft.getSelectedIndex()==7){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan/permintaan Anda. Tks");
        }
        if(cbdraft.getSelectedIndex()==8){
            txtmsg.setText("Pelanggan Yth. mengenai keluhan/permintaan Anda tentang xxxx, kami mohon informasi berupa xxxx. Tks");
        }
        if(cbdraft.getSelectedIndex()==9){
            txtmsg.setText("Terima kasih atas informasi Anda.");
        }
        if(cbdraft.getSelectedIndex()==10){
            txtmsg.setText("Pelanggan Yth. petugas kami akan segera menghubungi Anda. Tks");
        }
        if(cbdraft.getSelectedIndex()==11){
            txtmsg.setText("");
        }
}//GEN-LAST:event_cbdraftActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void cbcaltypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbcaltypeMouseClicked
        // TODO add your handling code here:
        btnsend.setEnabled(true);
    }//GEN-LAST:event_cbcaltypeMouseClicked

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        opdt();
        optm();
        stt();
        if (valid()==true){
            int p;
            int coma;
            String nm;
            tu = txtto.getText();
            //        coma = tu.
            index = tu.indexOf(',');
            System.out.print("\n index = "+index);
            p = tu.length();
            while (index != -1) {
                nm = tu.substring(0, index);
                tu = tu.substring(index + 1, p);
                sql="insert into log_sms (sms_date,sms_time,username,sms_to"
                        + ",ticket_id,sms_text,_direction,direction_type"
                        + ",_status,cust_name)"
                        + " values"
                        + " ('"+opdt+"', '"+optm+"', '"+CCanj.lbluser.getText()+"', '"+nm+"'"
                        + ", '"+id+"', '"+txtmsg.getText()+"', 1, '"+cbcaltype.getSelectedItem()+"'"
                        + ", 0,'"+cbcust.getSelectedItem()+"')";
                CCanj.jconn.SQLExecute(sql,CCanj.conn);
                index = tu.indexOf(',');
                p = tu.length();
                CCanj.s = "SMS|OUTBOUND\r\n";
                CCanj.kirimBroad();
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) {

                }
            }
            if(index==-1){
                sql="insert into log_sms (sms_date,sms_time,username,sms_to"
                        + ",ticket_id,sms_text,_direction,direction_type"
                        + ",_status,cust_name)"
                        + " values"
                        + " ('"+opdt+"', '"+optm+"', '"+CCanj.lbluser.getText()+"', '"+tu+"'"
                        + ", '"+id+"', '"+txtmsg.getText()+"', 1, '"+cbcaltype.getSelectedItem()+"'"
                        + ", 0,'"+cbcust.getSelectedItem()+"')";
                CCanj.jconn.SQLExecute(sql,CCanj.conn);
                CCanj.s = "SMS|OUTBOUND\r\n";
                CCanj.kirimBroad();
                Tic.btnsms.setEnabled(true);
                dispose();
            }
                JOptionPane.showMessageDialog(null, "SMS SENT", "MESSAGING",JOptionPane.WARNING_MESSAGE);
        }
        if(smstic==true){
            if (status==0 && asdep==0){
                sql="update tickets set _status=1, process_date='"+opdt+"', process_time='"+optm+"', process_username='"+CCanj.lbluser.getText()+"' where ticket_id='"+Tic.id+"' and ticket_no='"+txtnotic.getText()+"'";
                CCanj.jconn.SQLExecute(sql,CCanj.conn);
                status=1;
            }
            sql1="insert into log_tickets (log_date,log_time,username,user_level,ticket_id,_status,info,ticket_no) values ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+usrlvl+"','"+Tic.id+"','"+status+"','Outgoing sms \nTo : "+txtto.getText()+" \n\n "+txtmsg.getText()+"','"+txtnotic.getText()+"')";
            CCanj.jconn.SQLExecute(sql1, CCanj.conn);
            try{
                sql2="select note from tickets where ticket_id='"+Tic.id+"'";
                rs = CCanj.jconn.SQLExecuteRS(sql2, CCanj.conn);
                while(rs.next()){
                    solution=rs.getString(1);
                }
            }catch(Exception exc){
                System.err.println(exc.getMessage());
            }
            sql3="update tickets set note='"+solution+"\n"+CCanj.lbluser.getText()+"@"+opdt.substring(8, 10) + "/" + opdt.substring(5, 7) + "/" + opdt.substring(0, 4)+"\n"+optm.replaceAll(":",".")+"\nOutgoing sms \nTo : "+txtto.getText()+" \n\n "+txtmsg.getText()+"\n===' where ticket_id='"+Tic.id+"'";
            CCanj.jconn.SQLExecute(sql3,CCanj.conn);
        }
        smstic=false;
    }//GEN-LAST:event_btnsendActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton btnsrchcus;
    public static javax.swing.JComboBox cbcaltype;
    public static javax.swing.JComboBox cbcust;
    private javax.swing.JComboBox cbdraft;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbllimit;
    private javax.swing.JTextArea txtmsg;
    public static javax.swing.JTextField txtnotic;
    public static javax.swing.JTextField txtto;
    // End of variables declaration//GEN-END:variables


    private String sql;
    private String sql1;
    private String sql2;
    private String sql3;
    private ResultSet rs;
//    private JavaConnector jconn=new JavaConnector();
//    private Connection conn;

    private boolean valid(){
        boolean result;
        if(txtto.getText().equals("")||txtmsg.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Data must be complete","MESSAGING",JOptionPane.WARNING_MESSAGE);
            result=false;
        }else{
            result=true;
        }
        return result;
    }
    
    private void bersih(){
        txtto.setText("");
        txtmsg.setText("");
            //txtNim.requestFocus();
    }
            
                 private void opdt(){
          try{
              sql="select CURRENT_DATE";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  opdt=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
    }

        private void optm(){
            try{
              sql="select CURRENT_TIME";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  optm=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
        }
        private void usrlvl(){
                try{
                    sql="select _level from user_account where username='"+CCanj.lbluser.getText()+"'";
                    rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
                    while(rs.next()){
                        usrlvl=rs.getString(1);
                    }
                }catch(Exception e){
                    System.out.print(e);
                }
            }
        private void stt(){
                try{
                    sql="select _status, assign_dept from tickets where ticket_id='"+Tic.id+"' and ticket_no='"+txtnotic.getText()+"'";
                    rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
                    while(rs.next()){
                        status=Integer.parseInt(rs.getString(1));
                        asdep=Integer.parseInt(rs.getString(2));
                    }
                }catch(Exception e){
                    System.out.print(e);
                }
            }
    private void showCaltype(){
        try{
            cbcaltype.removeAllItems();

            sql="select data from _callertype";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcaltype.addItem(rs.getString(1));
            }
        }catch(Exception e){
            System.out.println(e);

        }
    }
    private void showCust(){
        try{
            cbcust.removeAllItems();
            cbcust.addItem("Others");

            sql="select distinct(fullname) from customers";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcust.addItem(rs.getString(1));
            }
            cbcust.setSelectedIndex(-1);
        }catch(Exception e){
            System.out.println(e);

        }
    }
}
