/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sms_income.java
 *
 * Created on Feb 23, 2010, 3:37:41 PM
 */

package cc_tunas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;
import java.awt.Event.*;
import java.sql.*;
import javax.sun.database.JavaConnector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import java.util.ArrayList;
/**
 *
 * @author jsm
 */
public class Sms_income extends javax.swing.JFrame {
    public static int z;
    public static int zz;
    public static int sid=0;
    private boolean selected;

    /** Creates new form Sms_income */
    public Sms_income() {
        initComponents();
        open();
        showCaltype();
        showCust();
        selected=false;
    }

    public Search_ticket Sct;
    public Sms_income(Search_ticket sct){
        this();
        this.Sct=sct;
    }
    public static ContactCenterTunas CCanj;
    public Sms_income(ContactCenterTunas ccanj){
        this();
        this.CCanj=ccanj;
    }
    public static SMS sMs;
    public Sms_income(SMS smS){
        this();
        this.sMs=smS;
    }
    private ticket Tic;
    public Sms_income(ticket tic){
        this();
        this.Tic=tic;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtmsg = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbcaltype = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cbcust = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtnotic = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("INCOMING MESSAGES");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        txtmsg.setColumns(20);
        txtmsg.setFont(new java.awt.Font("Calibri", 0, 11));
        txtmsg.setRows(5);
        jScrollPane3.setViewportView(txtmsg);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(110, 70, 440, 76);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel2.setText("Messages :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 70, 100, 20);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel1.setText("Sender        :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 20);

        txtto.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel1.add(txtto);
        txtto.setBounds(110, 10, 200, 24);

        jButton1.setFont(new java.awt.Font("Calibri", 0, 12));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1245117595_001_37.png"))); // NOI18N
        jButton1.setText("Search Ticket");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 150, 131, 24);

        jButton2.setFont(new java.awt.Font("Calibri", 0, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tic.jpg"))); // NOI18N
        jButton2.setText("Open Ticket");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 150, 133, 24);

        jButton3.setFont(new java.awt.Font("Calibri", 0, 12));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reply m.jpg"))); // NOI18N
        jButton3.setText("Reply");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(310, 10, 99, 41);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 10, 200, 20);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel4.setText("Sender Type");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 30, 100, 20);

        cbcaltype.setFont(new java.awt.Font("Calibri", 0, 12));
        cbcaltype.setMaximumRowCount(9);
        cbcaltype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        cbcaltype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcaltypeActionPerformed(evt);
            }
        });
        jPanel1.add(cbcaltype);
        cbcaltype.setBounds(110, 30, 200, 24);

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel16.setText("Cust. Company");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 50, 100, 20);

        cbcust.setFont(new java.awt.Font("Calibri", 0, 12));
        cbcust.setMaximumRowCount(9);
        cbcust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        jPanel1.add(cbcust);
        cbcust.setBounds(110, 50, 200, 24);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ticket No");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 50, 100, 20);

        txtnotic.setFont(new java.awt.Font("Calibri", 0, 12));
        jPanel1.add(txtnotic);
        txtnotic.setBounds(410, 50, 140, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ticket tic=new ticket();
        tic.setVisible(true);

        Tic.newtic=true;
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SMS coms=new SMS();
        coms.setVisible(true);

        sMs.txtto.setText(txtto.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Search_ticket st=new Search_ticket();
        st.setVisible(true);
        Sct.sms=true;
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        zz=(Tic.id);
        System.out.print(zz);
        if(sid!=0){
            if(zz==-1){
                sql = "update log_sms set"
                        + " _status=2 ,direction_type='"+cbcaltype.getSelectedItem()+"', cust_name='"+cbcust.getSelectedItem()+"'"
                        + " ticket_no='"+txtnotic.getText()+"'"
                        + " where sms_id='"+sid+"'";
                CCanj.jconn.SQLExecute(sql, CCanj.conn);

            }else{
                sql = "update log_sms set " +
                    "_status=2 " +
                    ", ticket_id='"+zz+"' ,direction_type='"+cbcaltype.getSelectedItem()+"', cust_name='"+cbcust.getSelectedItem()+"' " +
                    "where sms_id='"+sid+"'";
                CCanj.jconn.SQLExecute(sql, CCanj.conn);
            }
        }
        CCanj.sms();
//        try {
//            conn.close();
//        } catch (SQLException ex) {
//            System.err.println(ex.getMessage());
//        }
    }//GEN-LAST:event_formWindowClosed

    private void cbcaltypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcaltypeActionPerformed
        // TODO add your handling code here:
        selected=true;
    }//GEN-LAST:event_cbcaltypeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(selected==true){
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sms_income().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox cbcaltype;
    public static javax.swing.JComboBox cbcust;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextArea txtmsg;
    public static javax.swing.JTextField txtnotic;
    public static javax.swing.JTextField txtto;
    // End of variables declaration//GEN-END:variables

    public static String sql;
    public static String sql1;
    public static ResultSet rs;
//    public static JavaConnector jconn=new JavaConnector();
//    public static Connection conn;

    public static void open(){
        sql = "select * from log_sms " +
                    "where _direction=0 " +
                    "and _status=1 " +
                    "and username='"+ CCanj.lbluser.getText()+"'";
            rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
        try {
            while (rs.next()) {
                z++;
                sid=Integer.parseInt(rs.getString(1));
                txtto.setText(rs.getString(8).toString());
                txtmsg.setText(rs.getString(10).toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Sms_income.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void showCaltype(){
        try{
            cbcaltype.removeAllItems();

            sql="select data from _callertype";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcaltype.addItem(rs.getString(1));
            }
        }catch(Exception e){
            System.out.println(e);

        }
    }
    private void showCust(){
        try{
            cbcust.removeAllItems();
            cbcust.addItem("Others");

            sql="select distinct(fullname) from customers";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcust.addItem(rs.getString(1));
            }
        }catch(Exception e){
            System.out.println(e);

        }
    }
}
